name: Build Container

on:
  push:
    branches:
      - master
    paths:
      - "**"
  schedule:
    - cron: '17 5 * * 2'
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          tags: latest
          tag_with_sha: true
          repository: hello-python
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          registry: cuartifacts-platform-engineering-docker-local.jfrog.io
